### ISSUE TITLE
What version PyTorch used?

### ISSUE THREAD

**Issue by stevenewbold** [dajes/frame-interpolation-pytorch#2]
Hi,

What version of PyTorch did you use to create film_net_fp16.pt?  I need to uses libtorch 1.12.1 and I'm getting a lot of errors so wanted to check version compatibility.

Thanks

**Comment by dajes** [comment]
Hi, it was exported with torch 1.12.1. I'm not sure what errors have you encountered but there were some warnings when using the model in python. The new release fixes this issue and re-exports model with 2.1.1 which also may resolve your issue
